#LIST OF ENTITIES:
EntityList = "/iesl/data/meta/pubtator/entities.txt"
datadir = "/home/mkaur/Desktop/ptb/"
medpost_train_datadir = "/home/mkaur/Desktop/SeqAN_Medpost/medpost/tagged/"
train = "train.txt"
eval = "dev.txt"
test = "test.txt"
word2vec_emb_path = "/opt/MLS_db/word-embs/GoogleNews-vectors-negative300.bin"
glove_emb_path = "/home/mkaur/Desktop/glove.840B.300d.txt"
PRETRAINED_VECTORS = "/home/manpreetkaur/EE/word2vecTools/vectors.txt"
batch_size = 1
num_epochs = 5
lstm_size = 100
keep_prob = 0.7
max_grad_norm = 5
restore = False

crf = False
glove = False
word2vec = True